#!/usr/bin/env python3
"""Writes the manifest of the origin of the files of dn/src (dn/PROVENANCE.md) or checks that it is up to date.
Classes: OURS (our files: bootstrap/new, dn/compat/linux, new files after the first commit: MIT), CARVED (the classes of DN itself
cut out of the files that are excluded as a whole: RIT code), RIT (the notice of DN OSP in the head of the file), CONTRIB (a contributor of
DN OSP is named in the head: Cat, JO, AK155...: part of the public DN OSP release, no license of its own), NONE (upstream, no notice: part
of the public DN OSP release).
usage: dn-manifest.py [--check]   (from the root of the repository)"""
import os, re, sys

root = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
srcdirs = [os.path.join(root, 'dn', d) for d in ('src', 'archives', 'compat')]   # the sources of DN by role (dn/FILES.md)
ours = set()
for d in (os.path.join(root, 'bootstrap', 'new'), os.path.join(root, 'dn', 'compat', 'linux')):
    for f in os.listdir(d):
        if f != '.gitkeep':
            ours.add(f.lower())
renames = {}      # dn/renames.map: new name -> the name in the archive (a file renamed after the first commit keeps its class)
rp = os.path.join(root, 'dn', 'renames.map')
if os.path.exists(rp):
    for line in open(rp, encoding='utf-8'):
        if line.strip() and not line.startswith('#'):
            a, b = line.split()
            renames[a] = b
carved = set()
for line in open(os.path.join(root, 'bootstrap', 'carve.list'), encoding='utf-8'):
    m = re.match(r'(\w+)\s*<-', line)
    if m:
        carved.add(m.group(1).lower() + '.pas')

def head_class(path):
    head = '\n'.join(open(path, encoding='cp866', errors='replace').read().split('\n')[:60]).lower()
    if 'rit research labs' in head or 'dos navigator open source' in head or 'dos navigator/2 open source' in head or 'dos navigator /2 osp' in head:
        return 'RIT'
    if re.search(r'copyright|\(c\)|written by|\bby [a-z]+ [a-z]+|\(ak155\)|\(cat\)', head):
        return 'CONTRIB'
    return 'NONE'

def low_ext(f):
    return os.path.splitext(f)[1].lower()

classes = {'OURS': [], 'CARVED': [], 'RIT': [], 'CONTRIB': [], 'NONE': []}
for f, p in sorted(((f, os.path.join(d, f)) for d in srcdirs for f in os.listdir(d)), key=lambda t: t[0].lower()):
    if not os.path.isfile(p) or low_ext(f) in ('.o', '.ppu'):      # the objects of a stray compilation in the tree are not sources
        continue
    low = renames.get(f.lower(), f.lower())
    c = 'OURS' if (low in ours or f.lower() in ours) else 'CARVED' if low in carved else head_class(p)
    classes[c].append(f)

TEXT = {
 'OURS': ('Our files (MIT, see `LICENSE`)', 'Written by us: the replacements of the units that were excluded (their code is of Borland origin or of the Virtual Pascal runtime), the adapters to `tv/`, the system layer. They carry no notice of RIT Labs and are not derived from the files of the archive.'),
 'CARVED': ('Carved (the license of DN)', 'The classes of DN itself (not of Borland) that were cut out of the files excluded as a whole (`bootstrap/carve.list`), then rewritten where the audit asked for it (`bootstrap/rewrite/`). The notice of RIT Labs stays in the head.'),
 'RIT': ('Code of DN (the license of DN)', 'Files of the public DN OSP 2.14 with the notice of RIT Research Labs; changed by the edits of `bootstrap/edits/` (and after the first commit by ordinary commits). The notice must stay in each of them.'),
 'CONTRIB': ('Contributors of DN OSP', 'Files of the public DN OSP 2.14 whose heads name another author (Cat, JO, AK155...) and give no license of their own: they came in the same public release as the rest, and are used as part of it. This is the thing to ask the owner of the project about (PLAN.md).'),
 'NONE': ('Upstream without a notice', 'Files of the public DN OSP 2.14 with no notice in the head (small adapters, tables, include files). Part of the same release.'),
}

out = ['# Origin of the files of `dn/src`, `dn/archives`, `dn/compat`', '',
       'Generated by `bootstrap/tools/dn-manifest.py` (CI checks that it is up to date: `--check`). How the tree was made: [`bootstrap/README.md`](../bootstrap/README.md).',
       'The files that are not in the tables are not in the repository: the Borland-origin code, the Virtual Pascal runtime, the binaries of the archive.', '']
out.append('| Class | Files |')
out.append('|---|---|')
for c, (t, _) in TEXT.items():
    out.append('| %s | %d |' % (t, len(classes[c])))
out.append('')
for c, (t, d) in TEXT.items():
    out += ['## %s' % t, '', d, '', ', '.join('`%s`' % f for f in classes[c]) or '(none)', '']
text = '\n'.join(out)
path = os.path.join(root, 'dn', 'PROVENANCE.md')
if '--check' in sys.argv:
    if not os.path.exists(path) or open(path, encoding='utf-8').read() != text:
        sys.exit('dn/PROVENANCE.md is not up to date: run bootstrap/tools/dn-manifest.py')
    print('PROVENANCE.md ok')
else:
    open(path, 'w', encoding='utf-8').write(text)
    print({c: len(v) for c, v in classes.items()})
