#!/usr/bin/env python3
"""Writes dn/src/evnames.pas: the names of the commands (cmXxx of dn/src/commands.pas and of the units of tv/src) and of the keys (kbXxx of
tv/src/tvkeys.pas) for the log of the flight recorder (a number alone says little when somebody reads the log).
  tools/gen-evnames.py          write the unit
  tools/gen-evnames.py --check  exit 1 if the unit on the disk is not what the sources give (CI: tools/check-layout.sh)"""
import glob, os, re, sys

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(root, 'dn', 'src', 'evnames.pas')


def read(path):
    with open(path, encoding='utf-8', errors='replace') as f:
        return f.read()


def strip_comments(s):
    s = re.sub(r'\(\*.*?\*\)', '', s, flags=re.S)
    s = re.sub(r'\{.*?\}', '', s, flags=re.S)
    return re.sub(r'//[^\n]*', '', s)


def constants(path, prefix):
    out = []
    for m in re.finditer(r'\b(%s[A-Za-z0-9_]*)\s*=\s*(\$[0-9A-Fa-f]+|[0-9]+)\s*;' % prefix, strip_comments(read(path))):
        v = m.group(2)
        out.append((m.group(1), int(v[1:], 16) if v[0] == '$' else int(v)))
    return out


def merge(items):
    """value -> the names, in the order of the sources, no repeats"""
    d = {}
    for n, v in items:
        if v > 0xFFFF:
            continue
        d.setdefault(v, [])
        if n not in d[v]:
            d[v].append(n)
    return d


def table(name, d):
    keys = sorted(d)
    lines = ['  %s: array[0..%d] of TNameRec = (' % (name, len(keys) - 1)]
    for i, v in enumerate(keys):
        lines.append("    (V: %d; N: '%s')%s" % (v, '|'.join(d[v]), ',' if i < len(keys) - 1 else ''))
    lines.append('  );')
    return '\n'.join(lines)


def build():
    cm = []
    for p in sorted(glob.glob(os.path.join(root, 'tv', 'src', '*.pas'))) + [os.path.join(root, 'dn', 'src', 'commands.pas')]:
        cm += constants(p, 'cm')
    kb = constants(os.path.join(root, 'tv', 'src', 'tvkeys.pas'), 'kb')
    cmd, key = merge(cm), merge(kb)
    return """{ GENERATED by tools/gen-evnames.py from the constants of the commands (dn/src/commands.pas, tv/src) and of the keys (tv/src/tvkeys.pas): do not edit.
  The names for the log (flightrec.pas); a value with several names (the same number is used in several families of commands) shows them all,
  joined with '|'. MIT, see LICENSE. }
unit evnames;

{$mode objfpc}
{$H-}

interface

{ 'cmQuit' for the command 1; '' if the number has no name }
function CommandName(Cmd: Word): String;
{ 'kbF5' for a key code of Turbo Vision (the scan code above, the character below); '' if the code has no name }
function KeyCodeName(Code: Word): String;

implementation

type
  TNameRec = record
    V: Word;
    N: String[%d];
  end;

const
%s

%s

function Find(const T: array of TNameRec; V: Word): String;
var
  Lo, Hi, Mid: Integer;
begin
  Result := '';
  Lo := 0;
  Hi := High(T);
  while Lo <= Hi do
  begin
    Mid := (Lo + Hi) div 2;
    if T[Mid].V = V then
      Exit(T[Mid].N)
    else if T[Mid].V < V then
      Lo := Mid + 1
    else
      Hi := Mid - 1;
  end;
end;

function CommandName(Cmd: Word): String;
begin
  Result := Find(Commands, Cmd);
end;

function KeyCodeName(Code: Word): String;
begin
  Result := Find(Keys, Code);
end;

end.
""" % (max(len('|'.join(v)) for d in (cmd, key) for v in d.values()) + 1, table('Commands', cmd), table('Keys', key))


text = build()
if '--check' in sys.argv:
    cur = read(OUT) if os.path.exists(OUT) else ''
    if cur != text:
        print('dn/src/evnames.pas is not what tools/gen-evnames.py gives: run it and commit the file')
        sys.exit(1)
    sys.exit(0)
with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
    f.write(text)
print('wrote', OUT)
