#!/usr/bin/env python3
"""Makes the "shim" units that give DN the names it takes from the TV units that were replaced by
tv/ (views, defines, dialogs...): for every name of the list of a DN unit (spec/dn-boundary-*.md) that
tv/src declares at the top level of an interface, the shim declares the same name as an alias
(a type, a constant) or a wrapper (a procedure, a function). The names that tv/src does not have
are listed in the report; they are written by hand (dn/new/manual/UNIT.inc is included into the
shim when it exists).

usage: tools/gen-shim.py UNIT [SPEC] [OUT_DIR]
  UNIT     the name of a DN unit as in the spec, with or without .pas (e.g. _defines)
The output is OUT_DIR/UNIT.pas (default dn/new/gen) and a report on stdout.
"""
import re, sys, os, glob

unit = sys.argv[1].lower()
if unit.endswith('.pas'):
    unit = unit[:-4]
spec = sys.argv[2] if len(sys.argv) > 2 else 'spec/dn-boundary-dnosp214.md'
out_dir = sys.argv[3] if len(sys.argv) > 3 else 'dn/new/gen'
tvdir = 'tv/src'

# names of the unit from the spec
names = []
cur = None
for line in open(spec, encoding='utf-8'):
    m = re.match(r'## (\S+)\.pas ', line)
    if m:
        cur = m.group(1).lower()
        continue
    if cur == unit and line.strip() and not line.startswith('#'):
        for n, a, b in re.findall(r'([A-Za-z_][A-Za-z0-9_]*) \((\d+)/(\d+)\)', line):
            names.append((n, int(a)))

# declarations at the top level of the interface sections of tv/src
decls = {}          # lower name -> (unit, kind, real name, text)
for f in sorted(glob.glob(os.path.join(tvdir, 'tv*.pas'))):
    u = os.path.basename(f)[:-4]
    lines = open(f, encoding='utf-8').read().split('\n')
    # the interface part
    try:
        i0 = next(i for i, l in enumerate(lines) if l.strip().lower() == 'interface')
        i1 = next(i for i, l in enumerate(lines) if l.strip().lower() == 'implementation')
    except StopIteration:
        continue
    sect = None
    i = i0 + 1
    while i < i1:
        l = lines[i]
        s = l.rstrip()
        if re.match(r'^(const|type|var)\s*$', s, re.I):
            sect = s.strip().lower(); i += 1; continue
        m = re.match(r'^(function|procedure)\s+(\w+)', s, re.I)
        if m:
            sig = s
            while not sig.rstrip().endswith(';') and i + 1 < i1:
                i += 1; sig += ' ' + lines[i].strip()
            decls[m.group(2).lower()] = (u, 'routine', m.group(2), sig)
            sect = None; i += 1; continue
        if re.match(r'^(uses|implementation|\{|\(\*)', s) or (s and not s.startswith(' ') and not s.startswith('\t')):
            if not re.match(r'^\s*$', s) and not s.startswith('{'):
                sect = None if not re.match(r'^(const|type|var)', s, re.I) else sect
            i += 1; continue
        if sect in ('const', 'type', 'var'):
            m = re.match(r'^  (\w+)\s*(=|:)\s*(.*)$', s)
            if m:
                name, sep, rest = m.groups()
                if sect == 'type' and sep == '=':
                    decls[name.lower()] = (u, 'type', name, rest)
                elif sect == 'const' and sep == '=':
                    decls[name.lower()] = (u, 'const', name, rest)
                elif sect == 'const':
                    decls[name.lower()] = (u, 'tconst', name, rest)
                elif sect == 'var':
                    decls[name.lower()] = (u, 'var', name, rest)
        i += 1

used_units = []
types, consts, vars_, routines, missing = [], [], [], [], []
for n, uses in names:
    d = decls.get(n.lower())
    if not d:
        missing.append((n, uses)); continue
    u, kind, real, text = d
    if u not in used_units:
        used_units.append(u)
    if kind == 'type':
        types.append('  %s = %s.%s;' % (real, u, real))
    elif kind == 'const':
        consts.append('  %s = %s.%s;' % (real, u, real))
    elif kind == 'routine':
        routines.append((u, real, text))
    else:
        vars_.append((n, uses, u, kind))

os.makedirs(out_dir, exist_ok=True)
manual = os.path.join('dn/new/manual', unit + '.inc')
with open(os.path.join(out_dir, unit + '.pas'), 'w', encoding='utf-8') as o:
    o.write('{ Generated by tools/gen-shim.py from tv/src: %s of the DN unit %s. Do not edit. }\n' % (
        'the names that tv/ has', unit))
    o.write('unit %s;\n\n{$mode objfpc}{$H-}\n\ninterface\n\nuses\n  %s;\n\n' % (unit, ', '.join(used_units) or 'SysUtils'))
    if types:
        o.write('type\n' + '\n'.join(types) + '\n\n')
    if consts:
        o.write('const\n' + '\n'.join(consts) + '\n\n')
    for u, real, text in routines:
        o.write(text + '\n')
    if os.path.exists(manual):
        o.write('\n{$I ../manual/%s.inc}\n' % unit)
    o.write('\nimplementation\n\n')
    for u, real, text in routines:
        m = re.match(r'(function|procedure)\s+\w+\s*(\(.*\))?\s*(:\s*[\w\.]+)?\s*;', text, re.I)
        o.write('%s\nbegin\n  %s\nend;\n\n' % (text.rstrip(), 'Result := ' if text.lower().startswith('function') else ''))
    o.write('end.\n')
print('%s: %d names in the spec; %d aliased (types %d, consts %d), %d routines, %d variables or typed constants, %d missing' % (
    unit, len(names), len(types) + len(consts), len(types), len(consts), len(routines), len(vars_), len(missing)))
if vars_:
    print('variables / typed constants (by hand):', ', '.join('%s(%d)' % (v[0], v[1]) for v in vars_))
print('missing (by hand or not in tv/):', ', '.join('%s(%d)' % m for m in missing))
