#!/usr/bin/env python3
"""Makes the "shim" units: units with the names of the units of Borland Turbo Vision that DN uses (Views,
Dialogs, App, ...; the DN copies of them are replaced, PLAN.md decisions 6 and 11) that give the names
of our tv/ units. For every top-level name that the listed tv/src units declare in their interfaces the
shim declares the same name: a type or a constant as an alias (the members of an enumeration as
constants), a variable (or a typed constant) as `absolute` of the original, a procedure or function
as a wrapper. Nothing else is in the shim: what DN adds to TV is written by hand and included from
dn/new/manual/UNIT.inc (the interface part) and UNIT.impl.inc (the implementation part).

usage: tools/gen-shim.py MAP_FILE OUT_DIR [TV_SRC_DIR]
  MAP_FILE  lines `UnitName: TvUnit TvUnit ... [+OwnUnit]` (# comments; +OwnUnit goes to the uses only, -Name is a name that is not given, -Prefix* all the names that begin so); `*` = all the units tv/src/tv*.pas
  OUT_DIR   where UNIT.pas are written (dn/new is not used: the shims are generated by
            tools/dn-materialize.sh into the tree, not committed)
Prints one line per unit: how many names of which kind, and the names that were declared twice.
"""
import re, sys, os, glob

map_file, out_dir = sys.argv[1], sys.argv[2]
tvdir = sys.argv[3] if len(sys.argv) > 3 else 'tv/src'
manual_dir = os.path.join(os.path.dirname(os.path.abspath(map_file)), 'manual')

def split_top(s, sep):
    parts, depth, cur = [], 0, ''
    for ch in s:
        if ch in '([':
            depth += 1
        elif ch in ')]':
            depth -= 1
        if ch == sep and depth == 0:
            parts.append(cur); cur = ''
        else:
            cur += ch
    parts.append(cur)
    return parts

def parse_unit(path):
    """Top-level declarations of the interface: list of (kind, name, text)."""
    lines = open(path, encoding='utf-8').read().split('\n')
    try:
        i0 = next(i for i, l in enumerate(lines) if l.strip().lower() == 'interface')
        i1 = next(i for i, l in enumerate(lines) if l.strip().lower() == 'implementation')
    except StopIteration:
        return []
    res = []
    sect = None
    i = i0 + 1
    while i < i1:
        s = lines[i].rstrip()
        if re.match(r'^(const|type|var)\s*$', s, re.I):
            sect = s.strip().lower(); i += 1; continue
        m = re.match(r'^(function|procedure)\s+(\w+)', s, re.I)
        if m:
            sig = s
            def open_parens(t):
                t = re.sub(r'\{.*?\}', '', t)
                return t.count('(') - t.count(')')
            while i + 1 < i1 and (open_parens(sig) > 0 or not re.search(r';\s*(\{.*\})?\s*$', sig)):
                i += 1; sig += ' ' + lines[i].strip()
            res.append(('routine', m.group(2), re.sub(r'\{.*?\}', '', sig).strip()))
            sect = None; i += 1; continue
        if s and not s.startswith((' ', '\t', '{', '(*')) and not re.match(r'^(const|type|var)\b', s, re.I):
            sect = None; i += 1; continue
        m = re.match(r'^  (\w+)\s*(=|:)\s*(.*)$', s) if sect else None
        if m:
            name, sep, rest = m.groups()
            # a declaration may go on over several lines until a line that ends with ';' outside brackets
            text = rest
            depth = text.count('(') - text.count(')') + text.count('[') - text.count(']')
            kind_is_record = re.match(r'(packed\s+)?(object|record|class)\b', rest.strip(), re.I)
            while i + 1 < i1 and (depth > 0 or not re.search(r';\s*(\{.*\})?\s*$', text) or
                                  (kind_is_record and not re.search(r'^  end;', lines[i], re.I) and
                                   not re.match(r'^\s*end\s*;', lines[i], re.I))):
                if kind_is_record and re.match(r'^  end;', lines[i + 1], re.I):
                    i += 1; text += ' end;'; break
                i += 1
                text += ' ' + lines[i].strip()
                depth = text.count('(') - text.count(')') + text.count('[') - text.count(']')
                if not kind_is_record and depth <= 0 and re.search(r';\s*(\{.*\})?\s*$', text):
                    break
            text = re.sub(r'\{.*?\}', '', text).strip()
            if sect == 'type' and sep == '=':
                res.append(('type', name, text))
            elif sect == 'const' and sep == '=':
                res.append(('const', name, text))
            elif sect in ('const', 'var') and sep == ':':
                res.append(('var', name, text))
            elif sect == 'var':
                res.append(('var', name, text))
        i += 1
    return res

def unit_uses(path):
    t = open(path, encoding='utf-8').read()
    i = t.lower().find('\ninterface')
    m = re.search(r'\nuses\s+([^;]*);', t[i:], re.I) if i >= 0 else None
    return re.findall(r'\w+', m.group(1)) if m else []

def enum_members(text):
    m = re.match(r'^\(([^()]*)\)\s*;?$', text.strip())
    if not m:
        return []
    out = []
    for p in m.group(1).split(','):
        n = p.strip().split('=')[0].strip()
        if re.match(r'^\w+$', n):
            out.append(n)
    return out

def params_of(sig):
    m = re.match(r'(?:function|procedure)\s+\w+\s*', sig, re.I)
    rest = sig[m.end():]
    plist = ''
    if rest.startswith('('):
        depth = 0
        for k, ch in enumerate(rest):
            if ch == '(':
                depth += 1
            elif ch == ')':
                depth -= 1
                if depth == 0:
                    plist = rest[1:k]; rest = rest[k + 1:]; break
    names = []
    clean = []
    for p in split_top(plist, ';'):
        p = p.strip()
        if not p:
            continue
        lhs, _, rhs = p.partition(':') if ':' in p else (p, '', '')
        lhs = re.sub(r'^(const|var|out)\s+', '', lhs.strip(), flags=re.I)
        for n in lhs.split(','):
            names.append(n.strip())
        clean.append(re.sub(r'\s*=\s*[^;]*$', '', p) if '=' in p else p)
    ret = ''
    mm = re.match(r'\s*:\s*([\w\.\^]+)', rest)
    if mm:
        ret = mm.group(1)
    over = bool(re.search(r'\boverload\s*;', rest, re.I))
    return names, '; '.join(clean), ret, over

maps = []
for line in open(map_file, encoding='utf-8'):
    line = line.split('#')[0].strip()
    if ':' in line:
        u, units = line.split(':', 1)
        maps.append((u.strip(), units.split()))
allunits = sorted(glob.glob(os.path.join(tvdir, 'tv*.pas')))
cache = {}
os.makedirs(out_dir, exist_ok=True)
for shim, units in maps:
    plus = [x[1:] for x in units if x.startswith('+')]     # +Unit: only in the uses of the shim (DN's own units)
    minus = set(x[1:].lower() for x in units if x.startswith('-'))      # -Name: this name is not given
    units = [x for x in units if not x.startswith('+') and not x.startswith('-')]
    if units == ['*']:
        units = [os.path.basename(f)[:-4] for f in allunits]
    seen = {}
    types, consts, vars_, routines = [], [], [], []
    dup = []
    for u in units:
        path = os.path.join(tvdir, u.lower() + '.pas')
        if u not in cache:
            cache[u] = parse_unit(path) if os.path.exists(path) else []
        for kind, name, text in cache[u]:
            key = name.lower()
            if key in minus or any(m.endswith('*') and key.startswith(m[:-1]) for m in minus):
                continue
            if key in seen:
                dup.append(name); continue
            seen[key] = u
            if kind == 'type':
                types.append((u, name))
                for e in enum_members(text):
                    if e.lower() not in seen:
                        seen[e.lower()] = u
                        consts.append((u, e))
            elif kind == 'const':
                consts.append((u, name))
            elif kind == 'var':
                vars_.append((u, name, text))
            else:
                routines.append((u, name, text))
    with open(os.path.join(out_dir, shim + '.pas'), 'w', encoding='utf-8') as o:
        o.write('{ Generated by tools/gen-shim.py from tv/src: the names of the units %s under the DN name %s. Do not edit. }\n' % (', '.join(units), shim))
        extra = []
        for u in units:
            for d in unit_uses(os.path.join(tvdir, u.lower() + '.pas')):
                if d not in units and d not in extra and os.path.exists(os.path.join(tvdir, d.lower() + '.pas')):
                    extra.append(d)      # the types of the signatures of the wrappers come from there
        o.write('unit %s;\n\n{$mode objfpc}{$H-}\n\ninterface\n\nuses\n  %s;\n\n' % (shim, ', '.join(units + extra + plus)))
        if types:
            o.write('type\n' + '\n'.join('  %s = %s.%s;' % (n, u, n) for u, n in types) + '\n\n')
        if consts:
            o.write('const\n' + '\n'.join('  %s = %s.%s;' % (n, u, n) for u, n in consts) + '\n\n')
        if vars_:
            o.write('var\n')
            for u, n, text in vars_:
                m = re.match(r'^(.*?)(?:\s*=\s*.*)?;$', text)
                tp = (m.group(1) if m else text.rstrip(';')).strip()
                if tp.startswith(':'):
                    tp = tp[1:].strip()
                o.write('  %s: %s absolute %s.%s;\n' % (n, tp, u, n))
            o.write('\n')
        wrappers = []
        for u, n, sig in routines:
            names, plist, ret, over = params_of(sig)
            head_if = sig if sig.endswith(';') else sig + ';'
            head_if = re.sub(r'\binline\s*;', '', head_if, flags=re.I)
            o.write(head_if + '\n')
            kw = 'function' if sig.lower().startswith('function') else 'procedure'
            head = '%s %s%s%s;%s' % (kw, n, '(' + plist + ')' if plist else '', (': ' + ret) if ret else '', ' overload;' if over else '')
            call = '%s.%s%s' % (u, n, '(' + ', '.join(names) + ')' if names else '')
            wrappers.append('%s\nbegin\n  %s%s;\nend;\n' % (head, 'Result := ' if ret else '', call))
        if os.path.exists(os.path.join(manual_dir, shim.lower() + '.inc')):
            o.write('\n{$I manual/%s.inc}\n' % shim.lower())
        o.write('\nimplementation\n\n')
        o.write('\n'.join(wrappers))
        if os.path.exists(os.path.join(manual_dir, shim.lower() + '.impl.inc')):
            o.write('\n{$I manual/%s.impl.inc}\n' % shim.lower())
        o.write('\nend.\n')
    print('%s: %d types, %d constants, %d variables, %d routines from %d units%s' % (
        shim, len(types), len(consts), len(vars_), len(routines), len(units),
        '; declared twice: ' + ', '.join(dup[:8]) if dup else ''))
