#!/usr/bin/env python3
"""Generate dn/lib/localecp/localecp_tables.inc for ZIP charset decode.

Byte→Unicode maps for the single-byte pages used by github.com/unxed/localecp
getEncodingByName (python codecs ≈ golang.org/x/text/encoding/charmap).
Multi-byte pages (GBK, BIG5, CP932, CP949) are not generated; Pascal falls back
to raw bytes like a nil decoder.

usage: python3 tools/gen-localecp-tables.py > dn/lib/localecp/localecp_tables.inc
"""
from __future__ import annotations

PAGES = [
    ("Cp437", "cp437"),
    ("Cp850", "cp850"),
    ("Cp852", "cp852"),
    ("Cp855", "cp855"),
    ("Cp862", "cp862"),
    ("Cp866", "cp866"),
    ("Cp1250", "cp1250"),
    ("Cp1251", "cp1251"),
    ("Cp1252", "cp1252"),
    ("Cp1253", "cp1253"),
    ("Cp1254", "cp1254"),
    ("Cp1255", "cp1255"),
    ("Cp1256", "cp1256"),
    ("Cp1257", "cp1257"),
    ("Cp1258", "cp1258"),
    ("Cp874", "cp874"),
    ("Iso8859_4", "iso8859_4"),
]


def table(codec: str) -> list[int]:
    t: list[int] = []
    for b in range(256):
        if b < 0x80:
            t.append(b)
        else:
            try:
                c = bytes([b]).decode(codec)
                assert len(c) == 1
                t.append(ord(c))
            except UnicodeDecodeError:
                t.append(0xFFFD)
    return t


def main() -> None:
    print("{ Generated by tools/gen-localecp-tables.py — do not edit. }")
    print("{ Matches python codecs ≈ golang.org/x/text/encoding/charmap for localecp. }")
    print()
    print("type")
    print("  TCpMap = array[0..255] of Word;")
    print("  PCpMap = ^TCpMap;")
    print()
    print("const")
    for name, codec in PAGES:
        t = table(codec)
        print(f"  {name}: TCpMap = (")
        for i in range(0, 256, 8):
            row = ", ".join("$%04X" % v for v in t[i : i + 8])
            comma = "," if i < 248 else ""
            print(f"    {row}{comma}")
        print("  );")
        print()


if __name__ == "__main__":
    main()
